Stroopwafels/Models/OrderDetailsViewModel.cs
using Ordering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Stroopwafels.Models
{
    public class OrderDetailsViewModel
    {
        [Required]
        [Display(Name = "Naam")]
        public string Naam { get; set; }

        [Required]
        [Display(Name = "Delivery Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime DeliveryDate { get; set; }

        public IList<OrderRow> OrderRows { get; set; }

        public OrderDetailsViewModel()
        {
            this.OrderRows = new List<OrderRow>
            {
                new OrderRow(0, StroopwafelType.Gewoon),
                new OrderRow(0, StroopwafelType.Suikervrij),
                new OrderRow(0, StroopwafelType.Super)
            };
        }
    }
}

Stroopwafels/Models/OrderRow.cs
using Ordering;
using System.ComponentModel.DataAnnotations;

namespace Stroopwafels.Models
{
    public class OrderRow
    {
        [Required]
        public int Amount { get; set; }

        public StroopwafelType Type { get; set; }

        public string DisplayName => this.Type.ToString();

        public OrderRow()
        {
        }

        public OrderRow(int amount, StroopwafelType type)
        {
            Amount = amount;
            Type = type;
        }
    }
}

Stroopwafels/Models/OrderRowsExtension.cs
using Ordering;
using System.Collections.Generic;
using System.Linq;

namespace Stroopwafels.Models
{
    public static class OrderRowsExtension
    {
        public static IList<KeyValuePair<StroopwafelType, int>> ToKeyValueList(this IList<OrderRow> orderRows)
        {
            return orderRows.Select(orderRow => new KeyValuePair<StroopwafelType, int>(orderRow.Type, orderRow.Amount))
                            .ToList();
        }
    }
}

Stroopwafels/Models/OrderSuccessfulViewModel.cs
namespace Stroopwafels.Models
{
    public class OrderSuccessfulViewModel
    {
        public string SelectedSupplier { get; set; }
        public int Quantity { get; set; }
        public string TotalAmount { get; set; }
    }
}

Stroopwafels/Models/Quote.cs
namespace Stroopwafels.Models
{
    public class Quote
    {
        public string SupplierName { get; set; }

        public string TotalAmount { get; set; }
    }
}

Stroopwafels/Models/QuoteViewModel.cs
using System.Collections.Generic;

namespace Stroopwafels.Models
{
    public class QuoteViewModel
    {
        public IList<Quote> Quotes { get; set; }

        public IList<OrderRow> OrderRows { get; set; }

        public string SelectedSupplier { get; set; }

        public QuoteViewModel()
        {
            this.Quotes = new List<Quote>();
            this.OrderRows = new List<OrderRow>();
        }
    }
}

Stroopwafels/Controllers/StroopwafelController.cs
using Ordering;
using Ordering.Commands;
using Ordering.Queries;
using Stroopwafels.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Stroopwafels.Controllers
{
    public class StroopwafelController : Controller
    {
        private readonly QuotesQueryHandler _quotesQueryHandler;
        private readonly OrderCommandHandler _orderCommandHandler;

        public StroopwafelController(QuotesQueryHandler quotesQueryHandler,
                                     OrderCommandHandler orderCommandHandler)
        {
            _quotesQueryHandler = quotesQueryHandler;
            _orderCommandHandler = orderCommandHandler;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new OrderDetailsViewModel());
        }

        [HttpPost]
        public ActionResult GetQuotes(OrderDetailsViewModel formModel)
        {
            if (ModelState.IsValid)
            {
                var quotes = GetQuotesFor(formModel.OrderRows.ToKeyValueList());
                quotes = FilterOnDeliveryDate(quotes, formModel.DeliveryDate);

                var viewModel = new QuoteViewModel()
                {
                    Quotes = quotes.Select(quote => new Models.Quote { SupplierName = quote.Supplier.Name, TotalAmount = quote.TotalPricePresentation })
                                   .ToList(),
                    OrderRows = formModel.OrderRows,
                    SelectedSupplier = FindCheapestSupplier(quotes)
                };

                return View(viewModel);
            }

            return Index();
        }

        [HttpPost]
        public ActionResult Order(QuoteViewModel formModel)
        {
            if (ModelState.IsValid)
            {
                PlaceOrder(formModel.OrderRows.ToKeyValueList(), formModel.SelectedSupplier);

                var viewModel = new OrderSuccessfulViewModel()
                {
                    SelectedSupplier = formModel.SelectedSupplier,
                    Quantity = formModel.OrderRows.Sum(x => x.Amount),
                    TotalAmount = formModel.Quotes.Single(x => x.SupplierName.Equals(formModel.SelectedSupplier)).TotalAmount
                };

                return View(viewModel);
            }

            return Index();
        }

        private IList<Ordering.Quote> GetQuotesFor(IList<KeyValuePair<StroopwafelType, int>> orderDetails)
        {
            return _quotesQueryHandler.Handle(new QuotesQuery(orderDetails));
        }

        private IList<Ordering.Quote> FilterOnDeliveryDate(IList<Ordering.Quote> quotes, DateTime deliveryDate)
        {
            (quotes as List<Ordering.Quote>).RemoveAll(m => (deliveryDate.Date - DateTime.Now.Date).TotalDays < m.Supplier.DeliveryDays);

            return quotes;
        }

        private void PlaceOrder(IList<KeyValuePair<StroopwafelType, int>> orderDetails, string supplier)
        {
            _orderCommandHandler.Handle(new OrderCommand(orderDetails, supplier));
        }

        private string FindCheapestSupplier(IList<Ordering.Quote> quotes)
        {
            return quotes.OrderBy(q => q.TotalPrice)
                         .First().Supplier.Name;
        }

    }
}

Stroopwafels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bestellen", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Stroopwafels/Views/Stroopwafel/GetQuotes.cshtml
@model Stroopwafels.Models.QuoteViewModel
@{
    ViewBag.Title = "Stroopwafels bestellen";
}

<div class="jumbotron">
    <h1>Stroopwafels bestellen</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Order", "Stroopwafel", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <h2>Prijzen</h2>
            <p>
                <div class="row">Je bestelling:</div>

                @for (var i = 0; i < Model.OrderRows.Count; i++)
                {
                    @Html.HiddenFor(m => Model.OrderRows[i].Type);
                    @Html.HiddenFor(m => Model.OrderRows[i].Amount);
                    <div class="row">
                        <div>@Html.Label(Model.OrderRows[i].DisplayName)</div>
                        <div>@Html.Label(Model.OrderRows[i].Amount.ToString())</div>
                    </div>
                }

                <div class="row">Prijzen per leverancier:</div>
                @for (var i = 0; i < Model.Quotes.Count; i++)
                {
                    @Html.HiddenFor(m => Model.Quotes[i].SupplierName);
                    @Html.HiddenFor(m => Model.Quotes[i].TotalAmount);
                    <div class="row">
                        <div>
                            @Html.RadioButtonFor(m => Model.SelectedSupplier, Model.Quotes[i].SupplierName)
                            <label for="@Model.Quotes[i].SupplierName">@Model.Quotes[i].SupplierName</label>
                        </div>
                        <div>@Html.Label(Model.Quotes[i].TotalAmount)</div>
                    </div>
                }
            </p>
            <p><input type="submit" value="Stroopwafels bestellen" class="btn btn-default" />
            </p>

        }
    </div>
    
</div>

Stroopwafels/Views/Stroopwafel/Index.cshtml
@model Stroopwafels.Models.OrderDetailsViewModel
@{
    ViewBag.Title = "Stroopwafels bestellen";
}

<script>
    $(function () {
        $('.datepicker').datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true,
            changeyear: true
        });
</script>

<div class="jumbotron">
    <h1>Stroopwafels bestellen</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("GetQuotes", "Stroopwafel", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

        <div>
            @Html.LabelFor(m => m.Naam)
            @Html.TextBoxFor(m => m.Naam)
            @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(model => model.DeliveryDate)
            @Html.TextBoxFor(m=> m.DeliveryDate, new { @class = "date-picker" })
            @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })
        </div>

            <h2>Bestelling</h2>
            <p>
                Voer hier uw bestelling in:

                @for (var i = 0; i < Model.OrderRows.Count; i++)
                {
                    @Html.HiddenFor(m => Model.OrderRows[i].Type);
                    <div class="row">
                        <div>@Html.Label(Model.OrderRows[i].DisplayName)</div>
                        <div>@Html.TextBoxFor(m => Model.OrderRows[i].Amount)</div>
                    </div>
                }
            </p>
            <p>
                <input type="submit" value="Prijzen ophalen" class="btn btn-default" />
            </p>

        }
    </div>

</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryui")  
@Styles.Render("~/Content/cssjqryUi")  
  
 <script type="text/javascript">  
     $(document).ready(function () {  
         $("#DeliveryDate").datepicker({  
             dateFormat: "dd/M/yy",  
             changeMonth: true,  
             changeYear: true,  
             yearRange: "-60:+0",
             beforeShowDay: $.datepicker.noWeekends
         });  
     });  
</script>  
}

Stroopwafels/Views/Stroopwafel/Order.cshtml
@model Stroopwafels.Models.OrderSuccessfulViewModel
@{
    ViewBag.Title = "Geslaagde bestelling";
}

    <h4>U heeft totaal @Model.Quantity item besteld bij @Model.SelectedSupplier en die kost @Model.TotalAmount</h4>

<h2>Bestelling succesvol</h2>